# Generated by Django 5.2.1 on 2025-05-28 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Semla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bakery', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('picture', models.ImageField(upload_to='produkter/')),
                ('vegan', models.BooleanField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('kind', models.CharField(max_length=50)),
            ],
        ),
    ]
