# Generated by Django 5.2.1 on 2025-05-29 08:40

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Semla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bakery', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('picture', models.ImageField(upload_to='')),
                ('vegan', models.BooleanField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('kind', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('semla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='semla_django.semla')),
            ],
        ),
    ]
